#!/bin/bash

set -e

TARGET=$1
VERSION=$2
HOST_ARCH=$3

CANADIAN_BUILD=1

if [ -z "${HOST_ARCH}" ]; then
    CANADIAN_BUILD=0
fi

if [ -z "${VERSION}" ]; then
    VERSION=stable
fi

if [ -z "${TARGET}" ]; then
    echo "Usage: $0 <target> <version>"
    exit 1
fi

GCC_PACKAGE=""

if [ $CANADIAN_BUILD -eq 1 ]; then
    case $HOST_ARCH in
        x86_64)
            GCC_PACKAGE="gcc"
            GPP_PACKAGE="g++"
            HOST_PREFIX="x86_64-linux-gnu"
            ;;
        aarch64)
            GCC_PACKAGE="gcc-aarch64-linux-gnu"
            GPP_PACKAGE="g++-aarch64-linux-gnu"
            HOST_PREFIX="aarch64-linux-gnu"
            ;;
        mingw-w64)
            GCC_PACKAGE="gcc-mingw-w64-x86-64-win32"
            GPP_PACKAGE="g++-mingw-w64-x86-64-win32"
            HOST_PREFIX="x86_64-w64-mingw32"
            ;;
        loongarch64)
            GCC_PACKAGE=""
            GPP_PACKAGE=""
            HOST_PREFIX="loongarch64-unknown-linux-gnu"
            ;;
        *)
            echo "Unsupported host architecture: ${HOST_ARCH}"
            exit 1
            ;;
    esac
fi

# packages
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
    automake \
    bison \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    file \
    flex \
    g++ \
    gawk \
    gdb \
    git \
    gperf \
    help2man \
    libncurses-dev \
    libssl-dev \
    libtool-bin \
    lzip \
    make \
    ninja-build \
    meson \
    patch \
    pkg-config \
    python3 \
    rsync \
    sudo \
    texinfo \
    unzip \
    wget \
    xz-utils \
    libssl-dev \
    libffi-dev \
    "$GCC_PACKAGE" \
    "$GPP_PACKAGE"

# Install toolchain for loongarch64
if [ $CANADIAN_BUILD -eq 1 ] && [ "$HOST_ARCH" = "loongarch64" ]; then
    sudo mkdir -p /opt/x-tools
    curl -Lf https://github.com/loong64/cross-tools/releases/download/20250911/x86_64-cross-tools-loongarch64-unknown-linux-gnu-stable.tar.xz | tar xJf - -C /opt/x-tools
    rm -rf x86_64-cross-tools-loongarch64-unknown-linux-gnu-stable.tar.xz
    export PATH="/opt/x-tools/loongarch64-unknown-linux-gnu/bin:$PATH"
fi

# crosstool-ng
if [ ! -e /usr/bin/ct-ng ]; then
    curl -Lf https://github.com/crosstool-ng/crosstool-ng/archive/crosstool-ng-1.28.0.tar.gz | tar xzf -
    pushd crosstool-ng-crosstool-ng-1.28.0
    for i in ../targets/${TARGET}/*; do
        if [[ $i == *.patch ]]; then
            patch -Np1 -i $i
        fi
    done
    ./bootstrap
    ./configure --prefix=/usr
    make -j$(nproc)
    sudo make install
    popd
fi

# build
sudo mkdir -p /opt
sudo chmod 0777 /opt
mkdir -p build
cp targets/${TARGET}/${VERSION}/.config build/.config
if [ $CANADIAN_BUILD -eq 1 ]; then
    # Replace CT_HOST="" to real HOST_PREFIX
    sed -i "s/CT_HOST=\"\"/CT_HOST=\"${HOST_PREFIX}\"/g" build/.config
fi
if [ -e targets/${TARGET}/${VERSION}/patches ]; then
    rm -rf build/patches
    cp -r targets/${TARGET}/${VERSION}/patches build/
    # Replace CT_LOCAL_PATCH_DIR="REPLACE_ME" to real path
    sed -i "s@CT_LOCAL_PATCH_DIR=\"REPLACE_ME\"@CT_LOCAL_PATCH_DIR=\"$(realpath build/patches)\"@g" build/.config
fi
pushd build
export CT_ALLOW_BUILD_AS_ROOT_SURE=1
ct-ng build || { tail -n 500 build.log; exit $ERRCODE; }
popd

# tarball
sudo mv /opt/x-tools/${TARGET} .
sudo chown -R root:root ${TARGET}

FILE_NAME=""
if [ $CANADIAN_BUILD -eq 1 ]; then
    FILE_NAME="${HOST_PREFIX}-cross-tools-${TARGET}-${VERSION}"
else
    FILE_NAME="$(uname -m)-cross-tools-${TARGET}-${VERSION}"
fi
echo "FILE_NAME=${FILE_NAME}" >> "$GITHUB_OUTPUT"
sudo tar -cJf ${FILE_NAME}.tar.xz ${TARGET}
sudo sha256sum ${FILE_NAME}.tar.xz | awk '{ print $1 }' > ${FILE_NAME}.tar.xz.sha256