name: Release

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
        version:
          - stable
          - mainline
          - latest
          - baseline
        target:
          - loongarch64-unknown-linux-gnu
          - loongarch64-unknown-linux-musl
        exclude:
          - target: loongarch64-unknown-linux-musl
            version: baseline        
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Build
        run: |
          sudo rm -rf /opt/x-tools
          ./scripts/make ${{ matrix.target }} ${{ matrix.version }}

      - name: Generate file
        run: |
          file_name="$(uname -m)-cross-tools-${{ matrix.target }}-${{ matrix.version }}"
          echo "file_name=${file_name}" >> $GITHUB_ENV
          ls -al

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.file_name }}.tar.xz
          path: ${{ env.file_name }}.tar.xz
          if-no-files-found: error
          retention-days: 1
      - name: Upload checksum
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.file_name }}.tar.xz.sha256
          path: ${{ env.file_name }}.tar.xz.sha256
          if-no-files-found: error
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: release
          pattern: "*.tar.*"
          merge-multiple: true
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag_name="$(date +%Y%m%d)"
          echo "tag_name=${tag_name}" >> $GITHUB_ENV
          gh release create ${tag_name} --title "${tag_name}" --generate-notes || true
      - name: Generate checksums
        run: |
          echo "**Supported targets**: [${{ env.tag_name }}](https://github.com/${{ github.repository }}/tree/${{ env.tag_name }}#supported-targets)" > RELEASE.md
          sed -n '/## Supported targets/,/### Note/{ /## Supported targets/b; /### Note/b; p; }' README.md >> RELEASE.md
      - name: Upload artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in release/*.tar.xz; do
            # gh release upload ${{ env.tag_name }} $i $i.sha256
            gh release upload ${{ env.tag_name }} $i
          done
          gh release edit ${{ env.tag_name }} -F RELEASE.md
